### ISSUE TITLE
Blocking activities and quieting down debug messages

### ISSUE THREAD

**Issue by jaburgeson** [JarekToro/homebridge-roku-tv#4]
Thank you for creating this plugin!

So far, everything has been working great and love being able to control my TV via HomeKit.

A few things, is there a way to remove all of the different sources/channels from the activities listing?

I only need a few to show up and would love an Include or an Exclude feature for this.

Also, I notice every time the plugin polls the Roku TV it shows up in the logs.  Is there any way to have only the polls that don't succeed show up in order to quiet down all the clutter?

Thanks again so much and appreciate the work!

**Comment by Damien514** [comment]
Ditto! Really great plugin, but I would love to deactivate the logging of the pings, and would love to  get a way to select sources/channels displayed.

**Comment by JarekToro** [comment]
Check out the latest version.

Logs should be cleaned up.

Add this to your config to remove an app from the list.
This exclusion list effect every tv (If you have multiple Roku Tvs in your home)
The name must match correctly. See the logs after a restart to see the list of all the apps it found.
```bash
[RokuTV] Adding Input Netflix with info ID: 1569, TYPE: appl
```
Config
```json
        {
            "pollingInterval": 30000,
             "excludedApps": ["Netflix"]
            "platform": "RokuTV"
        }
```
