### ISSUE TITLE
Unable to Find Roku Tv on my network

### ISSUE THREAD

**Issue by LordZork** [JarekToro/homebridge-roku-tv#6]
I am new to Homebridge (sorry!).  I installed the plugin but have not seen anywhere what I am supposed to do to get my TV connected.  I have a TCL Roku TV.

[RokuTV] Error: Could not find any Roku devices after 10 seconds
    at RokuFinder.<anonymous> (/usr/local/lib/node_modules/homebridge-roku-tv-plugin/node_modules/roku-client/lib/discover.ts:136:11)
    at RokuFinder.emit (events.js:310:20)
    at Timeout.done (/usr/local/lib/node_modules/homebridge-roku-tv-plugin/node_modules/roku-client/lib/discover.ts:55:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

Any help would be much appreciated, thanks!

**Comment by JarekToro** [comment]
is your Home-bridge Device on the same network as your TV?

**Comment by LordZork** [comment]
Yes, same network.  Both are hardwired/use ethernet cable, connected to the same router.  Though, they are in two different parts of the house, both connected to different ethernet switches, but those switches are connected to the same router... both the device and TV are on the same network.

Also, I'm not sure what the below (sentence in bold) means/entails...

"The home app will only control the power state and the active app. **To control with the remote you have to have the remote turned on in the control center and navigate to that.**"

**Comment by JarekToro** [comment]
So you have to enable remote control in the roku tv settings. Try that. 
Also that text your referring too will make more sense when it is actually working.

**Comment by LordZork** [comment]
Enable remote control?  Hmm... I'll have to see if I can find that.  I have the official Roku app on my phone working, which lets me control my app on my iPhone.  I also already have the TV set up with Alexa and working.  Would that setting already be on then, for those things, or is this a different setting?  Also, it's a setting in the TV not the Roku app?

**Comment by JarekToro** [comment]
![81DD9072-E9FC-4F3A-BC40-E2B646C00E81](https://user-images.githubusercontent.com/4674003/82859251-38267d00-9ee4-11ea-8745-8a04e707b98f.jpeg)

Check this out.

**Comment by NateUT99** [comment]
Having a similar issue... Homebridge is running on a RPi connected via Ethernet, TCL TV wireless. They are on separate VLANs, but there are no rules in place to restrict traffic between the networks.

I was able to get the homebridge-roku3.0.0-alpha1 to work, but it hasn’t been updated in awhile. Would like to use something that is being maintained. 😀

**Comment by LordZork** [comment]
Ok, so I just found what is basically the same settings, only slightly different terminology and less description (the description included in what you provided is helpful)...

1.) **Settings > System > Advanced system settings > Control by mobile apps** (instead of "External control")

2.) Network access

- **Default** – 'Control by mobile apps' is enabled only on a private network address, and accepts commands only from private network address.
- **Permissive** – 'Control by mobile apps' is enabled always, but accepts commands only from private network addresses or the same subnet.
- **Disabled** – 'Control by mobile apps' is disabled.

I am going to try the "Permissive" feature and report back (btw, thanks for the fast response!).

**Comment by LordZork** [comment]
TV Found... works!!!

Ok, so, first I switched from "Default" to "Permissive" and restarted Homebridge.  Same issue/errors.  Then I restarted the TV and – after it was back on – restarted Homebridge again... and it found the TV!  Just added it to HomeKit!  Gonna test it out now.

Thanks so much for making this plugin and sharing it, and for the quick replies!! :)

**Comment by JarekToro** [comment]
No prob, thanks for being detailed in your solution very helpful for others.

**Comment by JarekToro** [comment]
@NateUT99 if that fix doesn’t work for you then open a new issue and we will work on it from there.

**Comment by iakobou** [comment]
I cannot see the device. External is set for TCL Roku. It does not show in Home or in Control Center ATV Remote. I noticed the config does not include IP info. TV and homebridge are both on same SSID and I have restarted both to no avail. Not sure what to do!

**Comment by iakobou** [comment]
NVM it worked--had to read the logs and follow instructions to add manually

**Comment by MikeTannenbaum** [comment]
How did you add it manually? I'm struggling to get homebridge to see the Roku,

`{
    "bridge": {
        "name": "Homebridge",
        "username": "XX",
        "port": 51364,
        "pin": "xxx-xx-xxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Kasa",
            "platform": "TplinkSmarthome",
            "devices": [
                {
                    "host": "192.168.123.4"
                },
                {
                    "host": "192.168.123.17"
                }
            ]
        },
        {
            "name": "TV",
            "pollingInterval": 3000,
            "platform": "RokuTV",
            "devices": [
                {
                    "host": "192.168.123.6"
                }
            ]
        }
    ]
}`

I see in the logs "[7/8/2020, 12:04:56 AM] [RokuTV] Initializing RokuTV platform..." but cannot get the device to show in homebridge
