### ISSUE TITLE
Siri commands

### ISSUE THREAD

**Issue by LordZork** [JarekToro/homebridge-roku-tv#7]
I apologize if this info is somewhere already (I looked but didn't find it)...

I am able to turn my TV on and off via Siri, but is it also possible to use Siri to change inputs or channels?  If so, how would I go about switching named inputs, as well as channels, via Siri?  I tried a few logical commands but didn't work.

Thanks!  Great plugin, btw!!

**Comment by JarekToro** [comment]
I have been unable todo that personally as I was curious about it also, a few searches on reddit and stuff It seems Siri does not support it. 

One guy mentioned making a scene for different channels then telling Siri to activate the Netflix Scene for example.
